[package]
name = "gcmd"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.14", features = ["tokio"] }
tokio = { version = "1", features = ["fs", "rt-multi-thread", "io-util", "process", "sync"] }
chrono = "0.4"
bytesize = "1.3"
dirs = "5"
portable-pty = "0.8"
vt100 = "0.15"
image = "0.25.9"
